language: node_js
node_js:
  - 8
cache:
  yarn: true
  directories:
    - .npm
script:
    - yarn lint
    - yarn test:ci
    - yarn build
    - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
    - codecov

