export const GET_ROUNDS_REQUEST = 'GET_ROUNDS_REQUEST';
export const GET_ROUNDS_SUCCESS = 'GET_ROUNDS_SUCCESS';
export const GET_ROUNDS_FAILURE = 'GET_ROUNDS_FAILURE';

export const GET_ROUND_REQUEST = 'GET_ROUND_REQUEST';
export const GET_ROUND_SUCCESS = 'GET_ROUND_SUCCESS';
export const GET_ROUND_FAILURE = 'GET_ROUND_FAILURE';
